### ISSUE TITLE
SQLite driver missing in all arm64 macOS builds (v0.21.8-0.21.9)

### ISSUE THREAD

**Issue by jonahkeegan** [steveyegge/beads#230]
## Environment
- **Platform**: macOS (Apple Silicon / arm64)
- **macOS Version**: [your version]
- **bd Versions Tested**: 0.21.8 (npm), 0.21.9 (Homebrew, GitHub release, source build)

## Problem
All arm64 macOS binaries fail with:
sql: unknown driver "sqlite" (forgotten import?)zone 

## Installation Methods Tested
All methods show identical SQLite driver errors:

1. **Homebrew** (steveyegge/beads tap)
   ```bash
   brew tap steveyegge/beads && brew install bd

2. npm package (@beads/bd v0.21.8)
   ```bash
   npm install -g @beads/bd

3. Official GitHub release (beads_0.21.9_darwin_arm64.tar.gz)

4. Built from source
   ```bash
   git clone https://github.com/steveyegge/beads.git
   cd beads && go build -o bd ./cmd/bd

## Verification
otool -L on all binaries shows no SQLite library linked:

   ```bash
   otool -L /opt/homebrew/bin/bd | grep -i sqlite
   # No output - SQLite missing
   ```

## Impact
Beads is completely non-functional on Apple Silicon Macs
Affects all standard installation paths
bd init, bd doctor, bd list all fail immediately

**Comment by jonahkeegan** [comment]
Diagnostics
 ├ Installation: .beads/ directory found
 ├ Git Hooks: Missing 1 recommended hook(s) ⚠
 │   Missing: pre-push
 ├ Database: Unable to read database version ✗
 │   Storage: SQLite
 ├ Issue IDs: Unable to open database ✗
 ├ CLI Version: 0.21.8 (latest: 0.21.9) ⚠
 ├ Database Files: Single database file
 ├ JSONL Files: No JSONL files found (database-only mode)
 ├ Daemon Health: No daemon running (will auto-start on next command)
 ├ DB-JSONL Sync: N/A (no JSONL file)
 ├ Permissions: Database file exists but cannot be opened ✗
 └ Dependency Cycles: Unable to open database ⚠
     sql: unknown driver "sqlite" (forgotten import?)

⚠ Warning: Missing 1 recommended hook(s)
  Fix: Run './examples/git-hooks/install.sh' to install recommended git hooks

✗ Error: Unable to read database version
  Fix: Database may be corrupted. Try 'bd migrate'

⚠ Warning: 0.21.8 (latest: 0.21.9)
  Fix: Upgrade to latest version:
  • Homebrew: brew upgrade bd
  • Script: curl -fsSL https://raw.githubusercontent.com/steveyegge/beads/main/scripts/install.sh | bash

✗ Error: Database file exists but cannot be opened
  Fix: Check database permissions: /tmp/test-beads/.beads/beads.db

**Comment by steveyegge** [comment]
Fixed in commit d91cc56 - enabled CGO in goreleaser config. This will be available in the next release.

**Comment by iamFIREcracker** [comment]
Assuming this should have been fixed in 0.22.0, I am afraid it's still not working:

```
$ bd doctor

Diagnostics
 ├ Installation: .beads/ directory found
 ├ Git Hooks: Missing 1 recommended hook(s) ⚠
 │   Missing: pre-push
 ├ Database: Unable to read database version ✗
 │   Storage: SQLite
 ├ Issue IDs: Unable to open database ✗
 ├ CLI Version: 0.22.0 (latest)
 ├ Database Files: Single database file
 ├ JSONL Files: Using issues.jsonl
 ├ Daemon Health: No daemon running (will auto-start on next command)
 ├ DB-JSONL Sync: Database cannot be opened but JSONL contains 135 issues ⚠
 │   sql: unknown driver "sqlite" (forgotten import?)
 ├ Permissions: Database file exists but cannot be opened ✗
 └ Dependency Cycles: Unable to open database ⚠
     sql: unknown driver "sqlite" (forgotten import?)

⚠ Warning: Missing 1 recommended hook(s)
  Fix: See https://github.com/steveyegge/beads/tree/main/examples/git-hooks for installation instructions

✗ Error: Unable to read database version
  Fix: Database may be corrupted. Try 'bd migrate'

⚠ Warning: Database cannot be opened but JSONL contains 135 issues
  Fix: Run 'bd import -i issues.jsonl --rename-on-import' to recover issues from JSONL

✗ Error: Database file exists but cannot be opened
  Fix: Check database permissions: /Users/.../.beads/beads.db
```

**Comment by jzillmann** [comment]
Running into the same (yesterday as well as today. brew - old version, npm with old and 0.22).
```
bd doctor

Diagnostics
 ├ Installation: .beads/ directory found
 ├ Git Hooks: Missing 1 recommended hook(s) ⚠
 │   Missing: pre-push
 ├ Database: Unable to read database version ✗
 │   Storage: SQLite
 ├ Issue IDs: Unable to open database ✗
 ├ CLI Version: 0.22.0 (latest)
 ├ Database Files: Single database file
 ├ JSONL Files: No JSONL files found (database-only mode)
 ├ Daemon Health: No daemon running (will auto-start on next command)
 ├ DB-JSONL Sync: N/A (no JSONL file)
 ├ Permissions: Database file exists but cannot be opened ✗
 └ Dependency Cycles: Unable to open database ⚠
     sql: unknown driver "sqlite" (forgotten import?)

⚠ Warning: Missing 1 recommended hook(s)
  Fix: See https://github.com/steveyegge/beads/tree/main/examples/git-hooks for installation instructions

✗ Error: Unable to read database version
  Fix: Database may be corrupted. Try 'bd migrate'

✗ Error: Database file exists but cannot be opened
  Fix: Check database permissions: /Users/jz/Projects/web/product-forge/.beads/beads.db
```

**Comment by jzillmann** [comment]
@steveyegge did our feedback reach you or should i open a new ticket ?

**Comment by rscorer** [comment]
I'm still seeing this, so built a version which included the --tag sqlite

```
git clone https://github.com/steveyegge/beads
cd beads
CGO_ENABLED=1 go build -tags sqlite ./cmd/bd
```

Now I'm getting this error on MacOS 26.1

```
 ├ Database: version pre-0.17.5 (very old) ⚠
 │   Storage: SQLite
```

I tried deleting the ./beads/beads.db and the entire ./beads directory, then ran `bd install --quiet` and continue to get that error.

```
bd doctor

Diagnostics
 ├ Installation: .beads/ directory found
 ├ Git Hooks: All recommended hooks installed
 │   Installed: post-merge, pre-push, pre-commit
 ├ Database: version pre-0.17.5 (very old) ⚠
 │   Storage: SQLite
 ├ Issue IDs: Unable to query issues ✗
 ├ CLI Version: 0.22.1 (latest)
 ├ Database Files: Single database file
 ├ JSONL Files: No JSONL files found (database-only mode)
 ├ Daemon Health: Daemon running (PID 57300, version 0.22.1)
 ├ DB-JSONL Sync: N/A (no JSONL file)
 ├ Permissions: All permissions OK
 └ Dependency Cycles: No circular dependencies detected

⚠ Warning: version pre-0.17.5 (very old)
  Fix: Run 'bd migrate' to upgrade database schema
```

Should I open a new issue?

**Comment by jonahkeegan** [comment]
This seems to have resolved the issue, very cool 👍
